import { EnvironmentConfig } from './i.config';

export const environment: EnvironmentConfig = {
    production: true,
    // apiURL: 'http://182.74.225.102:5589/isalaamapistaging/api/',
    // redirectDonationURL: 'http://182.74.225.102:5589/isalaamstaging/donations',
    // shareMosqueUri: 'http://182.74.225.102:5589/isalaamstaging/dashboard/',
    // mosqueLaunchURL: '/isalaamstaging/dashboard/',
    // redirectPartnerURL:'http://182.74.225.102:5589/isalaamstaging/mosque/controlcenter',

    // apiURL: 'https://isalaam.me/mosquehubapi/api/',
    // redirectDonationURL: 'https://isalaam.me/mosquehub/donations',
    // shareMosqueUri: 'https://isalaam.me/mosquehub/dashboard/',
    // mosqueLaunchURL: '/mosquehub/dashboard/',
    // redirectPartnerURL:'https://isalaam.me/mosquehub/mosque/controlcenter',
    // accountsUrl: 'http://108.137.198.133:8081/Accounts',

    // apiURL: 'https://isalaam.me/isalaamapistaging/api/',
    // redirectDonationURL: 'https://isalaam.me/isalaamstaging/donations',
    // shareMosqueUri: 'https://isalaam.me/isalaamstaging/dashboard/',
    // mosqueLaunchURL: '/isalaamstaging/dashboard/',
    // redirectPartnerURL:'https://isalaam.me/isalaamstaging/mosque/controlcenter',
    // accountsUrl: 'http://182.74.225.102:6080/Accounts',

    apiURL: 'https://staging.isalaam.me/api/',
    redirectDonationURL: 'https://staging.isalaam.me/donations',
    shareMosqueUri: 'https://staging.isalaam.me/dashboard/',
    mosqueLaunchURL: '/dashboard/',
    redirectPartnerURL: 'https://staging.isalaam.me/mosque/controlcenter',
    accountsUrl: 'https://182.74.225.102:6080/Accounts',

    GoogleMapAPIKey: 'AIzaSyD0puj9nF2OY8neU2F9n_YuJd7nMq_PVis',
    //GoogleMapAPIKey: 'AIzaSyCGR6t_SxA6udt0iWXxhu4RQtbAOmVHt8Y',
    //GoogleMapAPIKey: 'AIzaSyBrQ_3LohSNULsf1j4QrtnmVfLSfySanbY',
    //plinkURL:'https://secure2-staging.plink.co.id',
    plinkURL: 'https://secure2.plink.co.id',    
    firebaseConfig: {
        apiKey: 'AIzaSyDSF079Cbt8h47IY_VmsJ5dstG6tg6m3ss',
        authDomain: 'isalaam-9a0fe.firebaseapp.com',
        projectId: 'isalaam-9a0fe',
        storageBucket: 'isalaam-9a0fe.firebasestorage.app',
        messagingSenderId: '26475229983',
        appId: '1:26475229983:web:274cc3d3a1c232c0a3362a',
        measurementId: 'G-F526TM2VF4',
    },
    apiEndPoints: {
        signUpUser: 'UserAccess/NewUserSignUp',
        userLogOut: 'UserAccess/SignOutUser',
        // sendOtp: '/Auth/Request',
        verifyOtp: 'UserAccess/VerifyOtpForSignInSignUp',
        resendAuthOtp: 'UserAccess/ResendLoginOtp',
        generateOtp: 'UserAccess/GenerateOtpForSignIn',
        generateOtpEditProfile: 'UserAccess/GenerateOtpForEditProfile',
        InactiveAccount: 'UserAccess/InactiveUserAccount',

        //*********************** Mosques End Points ***********************//

        //getAllMosqueList: 'Mosque/GetAllMosques',
        getAllMosqueList: 'Mosque/GetAllMosquesWithOutFilters',
        getAllMosqueListFilter: 'Mosque/GetAllMosquesWithFilters',
        addNewMosque: 'Mosque/AddNewMosque',
        sendMosqueOnboardRequest: 'Mosque/AddNewMosqueOnBoardingRequest',
        getMosqueDetails: 'Mosque/GetMosqueProfileInfo',
        getMosqueDetailsWP: 'Mosque/GetMosqueProfileDetails',
        deactivateMosque: 'Mosque/ActivateOrDeactivateMosque',
        assignRoleUserToMosque: 'Mosque/AddRoleForMosque',
        updateExistingMosqueDetails: 'Mosque/UpdateExistMosque',
        searchUsersForAdminAssign: 'Mosque/GetUnAssignedUsersForMosque',
        getMosquesAssignedForUser: 'Mosque/GetMosquesByUserId',
        uploadMosqueProfileOrCoverImage:
            'Mosque/UploadMosqueProfileOrCoverImage',
        uploadMosqueCoverImage: 'Mosque/UploadMosqueCoverImage',
        getCoverPhotosForMosque: 'Mosque/GetCoverPhotosByMosquesId',
        deleteMosqueCoverImages: 'Mosque/DeleteMosqueCoverImages',
        getMosqueMembers: 'KeyMember/GetMosqueKeyMembers',
        verifyUserExistAsMember: 'MobileDynamicMenu/VerifyUserExistAsMember',
        getAssignedMosqueKeyMembers: 'KeyMember/GetAssingedMosqueKeyMembers',
        addMosqueMember: 'KeyMember/AddKeyMemberToMosque',
        updateMosquememberDetails: '',
        getMosqueMemberInfo: '',
        getVerseOfTheDay: 'Mosque/GetVerseOfTheDay',
        addOrEditVerseOfTheDay: 'Mosque/AddOrEditVerseOfTheDay',
        getKeyMemberTypes: 'KeyMember/GetKeyMemberTypes',
        getAllMosques: 'Mosque/GetMosquesList',
        getAccessLevels: 'Mosque/GetAccessLevels',
        getAssetInvoice: 'General/GeneratePdf',
        getCompleteMosqueDetails: 'Mosque/GetCompleteMosqueProfileData',
        getCompleteMosqueDetailsWNP: 'Mosque/GetCompleteMosqueProfileDataWNP',
        getNextPrayerForMosque: 'Mosque/GetMosqueNextPrayerByMosqueId',
        getUnAssignedAdminsForMosque: 'Mosque/GetUnAssignedAdminsForMosque',
        assignAdminForMosque: 'Mosque/MapUserForMosque',
        getEssentialProducts: 'Mosque/GetEssentialInventoryItems',
        getFollowerList: 'MobileDynamicMenu/MosqueFollowersList',
        toFollowMosque: 'MobileDynamicMenu/FollowTheMosqueByUser',
        getOnboardMosqueList: 'Mosque/GetOnboardMosqueList',
        approveOnboardRequest: 'Mosque/ApproveMosqueOnboardRequest',
        googleAuthentication: 'UserAccess/GoogleVerifyForSignInSignUp',
        dailyAyathData: 'Mosque/GetVerseOfTheDayByMonth',
        getHaditTopics: 'QuranPrayers/GetHaditTopiks',
        hadithTopicById: 'QuranPrayers/GetDailyHaditTopikById',

        //*********************** User Management End Points ***********************//
        getAllUsersList: 'UserAccess/GetAllUsersList',
        getAllRolesList: 'Role/GetAllRoles',
        updateUserStatus: 'UserAccess/ActiveOrDeactiveUser',
        getUserProfileById: 'UserAccess/GetUserProfileById',
        uploadUserProfileImage: 'UserAccess/UploadUserProfileImage',
        updateUserProfile: 'UserAccess/VerifyProfileChangeOtp',
        getAllRoles: 'UserAccess/GetAllRoles',
        getMenuBasedOnRoleId: 'UserAccess/GetMenuBasedOnRoleId',
        addOrUpdateRole: 'Role/AddOrUpdateRole',
        getUserActivitiesById: 'UserAccess/GetUserActivity',
        unRegisterDeviceId: 'UserAccess/UnRegisterUserDevice',
        deRegisterAll: 'UserAccess/DeRegisterUserDevice',
        getAllBanksList: 'Mosque/GetMosqueBanksList',
        getMosqueQrInfo: 'Mosque/GetMosqueQRInfo',
        addMosqueBank: 'Mosque/AddBankDetailsForMosque',
        InactiveMosqueBank: 'Mosque/InactiveMosqueBank',

        //*********************** Prayer End Points ***********************//
        getPrayersTimings: 'Prayer/GetTodayPrayersByCoordiantes',
        getWeatherReport: 'General/GetWeatherReport',
        switchUserRole: 'UserAccess/SwicthUserRole',
        getImamMasters: 'Imam/GetImamProfileMasterData',
        addImamProfile: 'Imam/UploadImamProfileData',
        getImamProfileData: 'Imam/GetImamProfileData',
        verifyImamProfile: 'Imam/VerifyIsImamProfileUploadOrNot',
        getUserProfileData: 'UserAccess/GetKeyMemberProfileById',
        getTodayAttendies: 'Prayer/GetTodayAttendies',

        //*********************** Common End Points ***********************//
        getLocationsBySearch: 'IslamicPlaces/GetAutocompleteSearch?input=',
        getUserNotifications: 'Prayer/getUserNotifications',
        getAvailableLanguages: 'General/GetAllLanguages',
        getAllTraslations: 'General/GetAllLanguageTranslations',
        updateTranslationRecord: 'General/UpdateTranslationRecord',

        //*********************** Donations End Points ***********************//
        getDonationTypes: 'Master/GetAllDonationTypes',
        savePaymentDetailsById: 'Mosque/CreateMoyasarPayment',
        //getAllTransactions: 'Mosque/GetAllMosqueDonations',
        getAllTransactions: 'General/GetXenditDonationTransactions',
        loaZakathData: 'IslamicPlaces/ZakatCalculatorLog',
        zakatCalculation: 'IslamicPlaces/GetZakatCalculatorList',
        calculationByZakatId: 'IslamicPlaces/GetCalculationByZakatID',
        deleteCalculation: 'IslamicPlaces/ZakatCalculatorDelete',
        getUserCurrencyType: 'IslamicPlaces/GetUserCurrencyType',
        getUserDonationTypes: 'Master/GetAllUserDonationTypes',
        getUpcomingEventsForMosque: 'Mosque/MosqueUpcomingEvents',
        donationConfirm: 'Gallery/CallPrismaLinkForDonation',
        plinkTransactionCallDetails: 'Gallery/CallPrismaLinkTransaction',
        checkRegMosqueXendit: 'General/CheckMosqueRegisterWithXenditOrNot',
        registerMosqueForXenditt: 'General/MosqueRegisterWithXendit',
        callXendittForDonation: 'General/CallXenditForDonation',
        getAllMasjidPayOuts: 'KeyMember/GetMosqueXenditAmoutPayOuts',
        getAllXenditTransactions: 'KeyMember/GetAllXenditTransactions',
        getAllPaymentTransactions: 'KeyMember/GetDonationPaymentTransactions',
        getMosqueAvailableBalance: 'KeyMember/GetMosqueBankAvailableBalance',
        getMosqueBankDetails: 'KeyMember/GetMosqueBankDetailsForPayOut',
        payOutXenditt: 'KeyMember/MosqueAmoutPayOutXendit',
        workOrderPaymentAms: 'General/WorkOderVendorPaymentToAMS',
        getDonationChartDetails: 'KeyMember/GetDonationChartDetails',

        //*********************** Master Data End Points ***********************//
        getAllParentCategories: 'Master/GetParentCategories',
        getChildCategories: 'Master/GetChildCategories?parentGuid=',
        getAllProductsByCategories: 'Master/GetProductsByCategory?categoryGuid=',        
        getAllParentCategoriesFilter: 'Master/GetParentCategoriesFilter',
        getChildCategoriesFilter: 'Master/GetChildCategoriesFilter',
        getAllProdsByCatFilter:'Master/GetProductsByCategoryFilter',
        addCategories: 'Master/AddOrUpdateCategories',
        addProducts: 'Master/AddOrUpdateProduct',
        getProductUom: 'Master/GetActiveProductUomList?uomType=',
        activeInactiveCategoryProduct: 'Master/ActiveInactiveCategoryProducts',
        donateAssetForMosque: 'Master/DonateAnAssetForMosque',
        donatedProductStatus: 'Master/UpdateDonatedProductStatus',
        masterCurrencyTypes: 'Master/GetAllCurrencyTypes',
        updateUserCurrencyType: 'Master/UpdateCurrencyType',
        getPendingAssets: 'Master/GetPendingAssetDonations',
        getAllProductsThresholdByCategory:
            'Master/GetProductsWithThresholdByCategory',
        getThrsholdProductsByMosque:
            'Master/GetThresholdProductsListByMosque?mosqueGuid=',
        addUpdateThrsholdProducts: 'Master/AddOrUpdateProductThreshold',
        getMosqueTypes: 'Master/GetMosqueTypes',
        getMasterLocations: 'Master/GetMasterLocations',
        facilityResources: 'Master/GetMosqueFacilitiesAndResources',
        getCountries: 'Master/GetCountriesData',
        getLocations: 'Master/GetLocationDataById',
        getAllPurposeDataList: 'Mosque/GetCustomDonationPurposeList',
        addPurposeData: 'Mosque/AddCustomDonationPurpose',
        updatePurposeData: 'Mosque/UpdateCustomDonationPurpose',
        getAllBankChargesList: 'KeyMember/GetAllBankChargesList',
        getBanksForPaymentMode: 'KeyMember/GetAvailableBankMethodsAndNames',
        getBanksCharges: 'KeyMember/GetAllBankChargesSubTotal',

        //*********************** Menu Management End Points ***********************//
        getNavigationList: 'UserAccess/GetWebSideMenu',
        addNewRoleMenuAction: 'Menu/AddNewRoleMenuAction',
        deleteRoleMenuAction: 'Menu/DeleteRoleMenuAction',
        getBusinessActions: 'Menu/GetMenuAssignedUnAssignedBusinessActions',
        getChildMenus: 'UserAccess/GetChildMenuBasedOnMenuIdRoleId',
        getParentMenuList: 'Menu/GetAllParentMenus',
        getChildMenusById: 'Menu/GetChildMenusByParentId',
        addParentMenu: 'Menu/AddNewParentMenu',
        addChildMenu: 'Menu/AddNewChildMenu',
        getAllBusinessActions: 'Menu/GetAllBusinessActions',
        addOrUpdateBusinessActions: 'Menu/AddOrUpdateBusinessAction',
        activeInactiveMenu: 'Menu/ActiveInactiveMasterMenu',

        //*********************** Inventory Management End Points ***********************//
        getAllSuppliers: 'Master/GetSuppliers?mosqueGuid=',
        addOrUpdateSuppliers: 'Master/AddOrUpdateSuppliers',
        activeInactiveSupplier: 'Master/ActiveInactiveSupplier',
        getAllInventoryProducts: 'Master/GetInventoryProductsList?mosqueGuid=',
        addMosqueInventoryProduct: 'Master/AddMosqueInventoryProduct',
        activeOrInactiveInventory: 'Master/ActiveInactiveInventoryProducts',
        inventoryTransaction: 'Master/GetInventoryTransactions?inventoryGuid=',
        stockOutInventoryProduct: 'Master/StockOutInventoryProducts',
        uploadInvoice: 'Master/UploadInvoice',

        createServiceCall: 'General/CreateOrUpdateServiceCalls',
        getVendorDetails: 'General/GetMappedVendorsList',
        getAllVendorDataList: 'General/GetAllVendorsList',
        getServiceCallList: 'General/GetServiceCallsData',
        getServiceCallChildList: 'General/GetServiceCallItemsData',
        updateServiceCallId: 'General/GetServiceCallAndItemsById',
        serviceCallIdStatusUpdate: 'General/SeriviceTicketStatusUpdate',
        getWorkOrderCounts: 'General/GetAdminSeriviceOrdersCounts',
        estimatedAmountAccept: 'General/UpdateServiceItemStatus',

        //*********************** Event Management End Points ***********************//
        getAllEvents: 'Mosque/GetAllEventsForMosque',
        getEventsByMonth: 'Mosque/EventCalenderForMosque',
        createNewEvent: 'Mosque/AddNewEventForMosque',
        updateExistingEventDetails: 'Mosque/UpdateExistEventForMosque',
        getEventDetailsById: 'Mosque/GetEventById',
        updateEventStatus: 'Mosque/CancelOrActiveInactiveEvent',
        getUpcomingEvents: 'Mosque/GetAllEventsForMosque',

        //*********************** Gallery End Points ***********************//
        getIslamicMediaChannels: 'VideoArticles/GetIslamicMediaChannels',
        addIslamicChannel: 'VideoArticles/AddNewIslamicMediaChannel',
        addIslamicVideo: 'VideoArticles/AddNewVideoArticles',
        getVideosAndArticles: 'VideoArticles/GetVideosAndArticles',
        getMediaGalleryImages: 'Gallery/GetMediaGallery',
        uploadMediaGallery: 'Gallery/UploadMediaGallery',
        deleteMediaGallery: 'Gallery/DeleteMediaGallery',
        deleteMediaGalleryVideos: 'VideoArticles/DeleteMediaGalleryVideos',
        deleteMediaGalleryChannels: 'VideoArticles/DeleteMediaGalleryChannels',
        downloadImage: 'Gallery/DownloadImage',
        partnerSignIn: 'General/PartnerCode',
        partnerOAuth: 'General/PartnerAuthorizationToken',
        energyCosumption: 'General/EnergyDeviceData',
        switchQueryData: 'General/SwitchQueryData',
        updateSwitchData: 'General/UpdateSynkSwitchData',
        TemperatureSensor: 'General/TemperatureDeviceData',
        PartnerRefreshToken: 'General/PartnerRefreshToken',
        SetAcTemperature: 'General/SetAcTemperature',
    },
    imageEndPoints: {
        logo: 'assets/images/logo/logo',
        menuLogo: 'assets/images/logo/menulogo.svg',
        menuRightLogo: 'assets/images/logo/iSalaam_Header_Logo.svg',
        menuLogoWithText: 'assets/images/logo/iSalaam_Header_Logo_RTL.svg',
        profileCoverImage: 'assets/images/ui/coverpage_bg.png',
        profileOverlayImage: 'assets/images/ui/profile_img.svg',
        dProfileOverlayImage: 'assets/images/ui/defprofile_img.png',
        loginLogo: 'assets/images/logo/iSalaam_Logo_Web_Login.svg',
        languageName: '../../assets/images/logo/language+name.svg',
        language_arabic:
            'assets/images/account_preferences/language_arabic.svg',
        browseIcon: 'assets/images/ui/table/globe.svg',
        language: 'assets/images/account_preference/language.svg',
        activeIcon: 'assets/images/ui/table/Active.svg',
        prayer_timing_sun: 'assets/images/ui/prayer_timing_sun.svg',
        deactive: 'assets/images/ui/table/deactive.svg',
        pendingVerification: 'assets/images/ui/table/pendingVerification.svg',
        moreIcon: 'assets/images/ui/more-vertical.svg',
        checkIcon: 'assets/icons/action/check.svg',
        alertIcon: 'assets/icons/action/alert-triangle.svg',
        donation_mosque: 'assets/images/ui/donation_mosque.svg',
        donation_Amount_Icon: 'assets/images/ui/icons/dnt_amount.svg',
        eventsBanner: 'assets/images/ui/events_banner.svg',
        ministryEvent: 'assets/images/ui/ministry-mosque-eventtype.svg',
        ministryEventInactive:
            'assets/images/ui/ministry-eventtype-inactive.svg',
        mosqueEvent: 'assets/images/ui/mosque-eventtype.svg',
        mosqueEventInactive: 'assets/images/ui/mosque_type_inactive.svg',
        dashboardSunIcon: 'assets/images/ui/cloud.sun.fill.svg',
        dashboardProfile: 'assets/images/ui/dashboard/solid-color-image.png',
        verseOfTheDay: 'assets/images/ui/dashboard/verse_bg.svg',
        verseOfTheDayIcon: 'assets/images/ui/dashboard/verse_bg_icon.png',
        reloadIcon: 'assets/images/ui/icons/u_redo.svg',
        deleteIcon: 'assets/images/ui/icons/fi_trash.svg',
        noMemberImage: 'assets/images/ui/no_member.svg',
        defaultMosqueImg: 'assets/images/ui/mosque_logos/default-mosque.png',
        sampleExcel: 'assets/reports/sample-excel/MMS-Vs-CMS.xlsx',
        menuIcons: {
            ministry: 'assets/icons/menu/ministry.svg',
            user: 'assets/icons/menu/user-settings.svg',
            prayers: 'assets/icons/menu/prayers.svg',
            events: 'assets/icons/menu/events.svg',
            donations: 'assets/icons/menu/donations.svg',
            reports: 'assets/icons/menu/reports.svg',
            otherServices: 'assets/icons/menu/otherServices.svg',
            techSupport: 'assets/icons/menu/techSupport.svg',
        },
        zakatCalculator: 'assets/images/zakat/zakat-calc.jpg',
        trashIcon: 'assets/icons/zakat/trash.png',
        assetDonation: 'assets/images/zakat/asset-donation.png',
        thresholdAsset: 'assets/images/zakat/threshold-asset.png',
        powerIcon: 'assets/images/kiot/power.png',
        temperatureIcon: 'assets/images/kiot/temperature-icon.png',
        AirConditioner: 'assets/images/kiot/AirConditioner.png',
        waterDropIcon: 'assets/images/kiot/waterdrop.png',
        followerIcon: 'assets/images/zakat/follower.png',
        attendiesIcon: 'assets/images/zakat/today-attendies.png',
        bankImage: 'assets/images/logo/bank-1.svg',
    },
};
