// bank-list.ts
export const bankList = [
    { channelCode: "ID_ACEH", bankName: "Bank Pembangunan Daerah Aceh" },
    { channelCode: "ID_ACEH_UUS", bankName: "Bank Pembangunan Daerah Aceh Syariah (UUS)" },
    { channelCode: "ID_AGRONIAGA", bankName: "Bank Raya Indonesia" },
    { channelCode: "ID_ALADIN", bankName: "Bank Aladin Syariah" },
    { channelCode: "ID_ALLO", bankName: "Allo Bank Indonesia" },
    { channelCode: "ID_AMAR", bankName: "Bank Amar Indonesia" },
    { channelCode: "ID_ANZ", bankName: "Bank ANZ Indonesia"},
    { channelCode: "ID_ARTHA", bankName: "Bank Artha Graha International"},
    { channelCode: "ID_BALI", bankName: "Bank Pembangunan Daerah Bali"},
    { channelCode: "ID_BAML", bankName: "Bank of America Merill-Lynch"},
    { channelCode: "ID_BANTEN", bankName: "Bank Pembangunan Daerah Banten" },
    { channelCode: "ID_BCA", bankName: "Bank Central Asia (BCA)" },
    { channelCode: "ID_BCA_DIGITAL", bankName: "Bank Central Asia Digital" },
    { channelCode: "ID_BCA_SYR", bankName: "Bank Central Asia (BCA) Syariah" },
    { channelCode: "ID_BENGKULU", bankName: "Bank Pembangunan Daerah Bengkulu" },
    { channelCode: "ID_BISNIS_INTERNASIONAL", bankName: "Bank Bisnis Internasional" },
    { channelCode: "ID_BJB", bankName: "Bank BJB" },
    { channelCode: "ID_BJB_SYR", bankName: "Bank BJB Syariah" },
    { channelCode: "ID_BNC", bankName: "Bank Neo Commerce" },
    { channelCode: "ID_BNI", bankName: "Bank Negara Indonesia (BNI)" },
    { channelCode: "ID_BNP_PARIBAS", bankName: "Bank BNP Paribas" },
    { channelCode: "ID_BOC", bankName: "Bank of China (BOC)" },
    { channelCode: "ID_BRI", bankName: "Bank Rakyat Indonesia (BRI)" },
    { channelCode: "ID_BSI", bankName: "Bank Syariah Indonesia (BSI)" },
    { channelCode: "ID_BTN", bankName: "Bank Tabungan Negara (BTN)" },
    { channelCode: "ID_BTN_UUS", bankName: "Bank Tabungan Negara Syariah (BTN UUS)" },
    { channelCode: "ID_BTPN_SYARIAH", bankName: "BTPN Syariah" },
    
    // Newly added banks
    { channelCode: "ID_BUKOPIN", bankName: "Bank Bukopin" },
    { channelCode: "ID_BUKOPIN_SYR", bankName: "Bank Syariah Bukopin" },
    { channelCode: "ID_BUMI_ARTA", bankName: "Bank Bumi Arta" },
    { channelCode: "ID_CAPITAL", bankName: "Bank Capital Indonesia" },
    { channelCode: "ID_CCB", bankName: "China Construction Bank Indonesia" },
    { channelCode: "ID_CHINATRUST", bankName: "Bank Chinatrust Indonesia" },
    { channelCode: "ID_CIMB", bankName: "Bank CIMB Niaga" },
    { channelCode: "ID_CIMB_UUS", bankName: "Bank CIMB Niaga Syariah (UUS)" },
    { channelCode: "ID_CITIBANK", bankName: "Citibank" },
    { channelCode: "ID_COMMONWEALTH", bankName: "Bank Commonwealth" },
    { channelCode: "ID_DAERAH_ISTIMEWA", bankName: "Bank Pembangunan Daerah Daerah Istimewa Yogyakarta (DIY)" },
    { channelCode: "ID_DAERAH_ISTIMEWA_UUS", bankName: "Bank Pembangunan Daerah Daerah Istimewa Yogyakarta Syariah (DIY UUS)" },
    { channelCode: "ID_DANAMON", bankName: "Bank Danamon" },
    { channelCode: "ID_DANAMON_UUS", bankName: "Bank Danamon Syariah (UUS)" },
    { channelCode: "ID_DBS", bankName: "Bank DBS Indonesia" },
    { channelCode: "ID_DEUTSCHE", bankName: "Deutsche Bank" },
    { channelCode: "ID_DINAR_INDONESIA", bankName: "Bank Dinar Indonesia" },
    { channelCode: "ID_DKI", bankName: "Bank DKI" },
    { channelCode: "ID_DKI_UUS", bankName: "Bank DKI Syariah (UUS)" },
    { channelCode: "ID_FAMA", bankName: "Bank Fama International" },
    { channelCode: "ID_GANESHA", bankName: "Bank Ganesha" },
    { channelCode: "ID_HANA", bankName: "Bank Hana" },
    { channelCode: "ID_HSBC", bankName: "HSBC Indonesia" },
    { channelCode: "ID_HSBC_UUS", bankName: "Hongkong and Shanghai Bank Corporation Syariah" },
    { channelCode: "ID_IBK", bankName: "Bank IBK Indonesia" },
    { channelCode: "ID_ICBC", bankName: "Bank ICBC Indonesia" },
    { channelCode: "ID_INA_PERDANA", bankName: "Bank Ina Perdania" },
    { channelCode: "ID_INDEX_SELINDO", bankName: "Bank Index Selindo" },
    { channelCode: "ID_INDIA", bankName: "Bank of India Indonesia" },
    { channelCode: "ID_JAGO", bankName: "Bank Jago" },
    { channelCode: "ID_JAMBI", bankName: "Bank Pembangunan Daerah Jambi" },
    { channelCode: "ID_JAMBI_UUS", bankName: "Bank Pembangunan Daerah Jambi Syariah" },
    { channelCode: "ID_JASA_JAKARTA", bankName: "Bank Jasa Jakarta" },
    { channelCode: "ID_JAWA_TENGAH", bankName: "Bank Pembangunan Daerah Jawa Tengah" },
    { channelCode: "ID_JAWA_TENGAH_UUS", bankName: "Bank Pembangunan Daerah Jawa Tengah Syariah" },
    { channelCode: "ID_JAWA_TIMUR", bankName: "Bank Pembangunan Daerah Jawa Timur" },
    { channelCode: "ID_JAWA_TIMUR_UUS", bankName: "Bank Pembangunan Daerah Jawa Timur Syariah" },
    { channelCode: "ID_JPMORGAN", bankName: "JP Morgan Chase Bank" },
    { channelCode: "ID_JTRUST", bankName: "Bank JTrust Indonesia" },
    { channelCode: "ID_KALIMANTAN_BARAT", bankName: "Bank Pembangunan Daerah Kalimantan Barat" },
    { channelCode: "ID_KALIMANTAN_BARAT_UUS", bankName: "Bank Pembangunan Daerah Kalimantan Barat Syariah (UUS)" },
    { channelCode: "ID_KALIMANTAN_SELATAN", bankName: "Bank Pembangunan Daerah Kalimantan Selatan" },
    { channelCode: "ID_KALIMANTAN_SELATAN_UUS", bankName: "Bank Pembangunan Daerah Kalimantan Selatan Syariah (UUS)" },
    { channelCode: "ID_KALIMANTAN_TENGAH", bankName: "Bank Pembangunan Daerah Kalimantan Tengah" },
    { channelCode: "ID_KALIMANTAN_TIMUR", bankName: "Bank Pembangunan Daerah Kalimantan Timur" },
    { channelCode: "ID_KALIMANTAN_TIMUR_UUS", bankName: "Bank Pembangunan Daerah Kalimantan Timur Syariah (UUS)" },
    { channelCode: "ID_LAMPUNG", bankName: "Bank Pembangunan Daerah Lampung" },
    { channelCode: "ID_MALUKU", bankName: "Bank Pembangunan Daerah Maluku" },
    { channelCode: "ID_MANDIRI", bankName: "Bank Mandiri" },
    { channelCode: "ID_MANDIRI_TASPEN", bankName: "Mandiri Taspen Pos" },
    { channelCode: "ID_MASPION", bankName: "Bank Maspion Indonesia" },
    { channelCode: "ID_MAYAPADA", bankName: "Bank Mayapada International" },
    { channelCode: "ID_MAYBANK", bankName: "Bank Maybank" },
    { channelCode: "ID_MAYORA", bankName: "Bank Mayora" },
    { channelCode: "ID_MEGA", bankName: "Bank Mega" },
    { channelCode: "ID_MEGA_SYR", bankName: "Bank Syariah Mega" },
    { channelCode: "ID_MESTIKA_DHARMA", bankName: "Bank Mestika Dharma" },
    { channelCode: "ID_MIZUHO", bankName: "Bank Mizuho Indonesia" },
    { channelCode: "ID_MNC_INTERNASIONAL", bankName: "Bank MNC Internasional" },
    { channelCode: "ID_MUAMALAT", bankName: "Bank Muamalat Indonesia" },
    { channelCode: "ID_MULTI_ARTA_SENTOSA", bankName: "Bank Multi Arta Sentosa" },
    { channelCode: "ID_NATIONALNOBU", bankName: "Bank Nationalnobu" },
    { channelCode: "ID_NUSA_TENGGARA_BARAT", bankName: "Bank Pembangunan Daerah Nusa Tenggara Barat" },
    { channelCode: "ID_NUSA_TENGGARA_TIMUR", bankName: "Bank Pembangunan Daerah Nusa Tenggara Timur" },
    { channelCode: "ID_OCBC", bankName: "Bank OCBC NISP" },
    { channelCode: "ID_OCBC_UUS", bankName: "Bank OCBC NISP Syariah (UUS)" },
    { channelCode: "ID_OKE", bankName: "Bank Oke Indonesia" },
    { channelCode: "ID_PANIN", bankName: "Bank Panin" },
    { channelCode: "ID_PANIN_SYR", bankName: "Bank Panin Syariah" },
    { channelCode: "ID_PAPUA", bankName: "Bank Pembangunan Daerah Papua" },
    { channelCode: "ID_PERMATA", bankName: "Bank Permata" },
    { channelCode: "ID_PERMATA_UUS", bankName: "Bank Permata Syariah (UUS)" },
    { channelCode: "ID_PRIMA_MASTER", bankName: "Prima Master Bank" },
    { channelCode: "ID_QNB_INDONESIA", bankName: "Bank QNB Indonesia" },
    { channelCode: "ID_RABOBANK", bankName: "Bank Rabobank International Indonesia" },
    { channelCode: "ID_RESONA", bankName: "Bank Resona Perdania" },
    { channelCode: "ID_RIAU_DAN_KEPRI", bankName: "Bank Pembangunan Daerah Riau Dan Kepri" },
    { channelCode: "ID_SAHABAT_SAMPOERNA", bankName: "Bank Sahabat Sampoerna" },
    { channelCode: "ID_SBI_INDONESIA", bankName: "Bank SBI Indonesia" },
    { channelCode: "ID_SEABANK", bankName: "Bank Seabank Indonesia" },
    { channelCode: "ID_SHINHAN", bankName: "Bank Shinhan Indonesia" },
    { channelCode: "ID_SINARMAS", bankName: "Bank Sinarmas" },
    { channelCode: "ID_SINARMAS_UUS", bankName: "Bank Sinarmas Syariah (UUS)" },
    { channelCode: "ID_STANDARD_CHARTERED", bankName: "Standard Charted Bank" },
    { channelCode: "ID_SULAWESI", bankName: "Bank Pembangunan Daerah Sulawesi Tengah" },
    { channelCode: "ID_SULAWESI_TENGGARA", bankName: "Bank Pembangunan Daerah Sulawesi Tenggara" },
    { channelCode: "ID_SULSELBAR", bankName: "Bank Pembangunan Daerah Sulselbar" },
    { channelCode: "ID_SULSELBAR_UUS", bankName: "Bank Pembangunan Daerah Sulselbar Syariah (UUS)" },
    { channelCode: "ID_SULUT", bankName: "Bank Pembangunan Daerah Sulut" },
    { channelCode: "ID_SUMATERA_BARAT", bankName: "Bank Pembangunan Daerah Sumatera Barat" },
    { channelCode: "ID_SUMATERA_BARAT_UUS", bankName: "Bank Pembangunan Daerah Sumatera Barat Syariah (UUS)" },
    { channelCode: "ID_SUMSEL_DAN_BABEL", bankName: "Bank Pembangunan Daerah Sumsel Dan Babel" },
    { channelCode: "ID_SUMSEL_DAN_BABEL_UUS", bankName: "Bank Pembangunan Daerah Sumsel Dan Babel Syariah (UUS)" },
    { channelCode: "ID_SUMUT", bankName: "Bank Pembangunan Daerah Sumut" },
    { channelCode: "ID_SUMUT_UUS", bankName: "Bank Pembangunan Daerah Sumut Syariah (UUS)" },
    { channelCode: "ID_TABUNGAN_PENSIUNAN_NASIONAL", bankName: "Bank Tabungan Pensiunan Nasional (BTPN)" },
    { channelCode: "ID_TOKYO", bankName: "Bank of Tokyo Mitsubishi UFJ (MUFJ)" },
    { channelCode: "ID_UOB", bankName: "Bank UOB Indonesia" },
    { channelCode: "ID_VICTORIA_INTERNASIONAL", bankName: "Bank Victoria Internasional" },
    { channelCode: "ID_VICTORIA_SYR", bankName: "Bank Victoria Syariah" },
    { channelCode: "ID_WOORI", bankName: "Bank Woori Indonesia" }
  ];
  